### ISSUE TITLE
MaxIDE fails to compile on OS X 10.9.5

### ISSUE THREAD

**Issue by melting-wax** [bmx-ng/bmx-ng#71]
Ran the MaxIDE build script as described in the releases section, and it failed with the following error the first time I tried it

```
[  0%] Compiling:appstub.macos.m
[  0%] Compiling:system.macos.m
[  1%] Compiling:timer.macos.m
[  1%] Compiling:cocoa.macos.m
[  2%] Compiling:NSProcessInfo_PECocoaBackports.m
[  2%] Compiling:macos.m
/Users/xxxx/bmx/BlitzMax/mod/brl.mod/appstub.mod/appstub.macos.m: In function 'main':
/Users/xxxx/bmx/BlitzMax/mod/brl.mod/appstub.mod/appstub.macos.m:100:2: error: stray '@' in program
  @autoreleasepool {
  ^
/Users/xxxx/bmx/BlitzMax/mod/brl.mod/appstub.mod/appstub.macos.m:100:3: error: 'autoreleasepool' undeclared (first use in this function); did you mean 'NSAutoreleasePool'?
  @autoreleasepool {
   ^~~~~~~~~~~~~~~
   NSAutoreleasePool
/Users/xxxx/bmx/BlitzMax/mod/brl.mod/appstub.mod/appstub.macos.m:100:3: note: each undeclared identifier is reported only once for each function it appears in
/Users/xxxx/bmx/BlitzMax/mod/brl.mod/appstub.mod/appstub.macos.m:100:18: error: expected ';' before '{' token
  @autoreleasepool {
                  ^~
                  ;
Build Error: failed to compile (256) /Users/xxxx/bmx/BlitzMax/mod/brl.mod/appstub.mod/appstub.macos.m%                                                                             /Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m: In function '+[CocoaApp delayedGadgetAction:]':
/Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m:171:1: note: previous declaration of '+(void)delayedGadgetAction:(NSNotification *)n'
 +(void)delayedGadgetAction:(NSNotification*)n;
 ^
In file included from /System/Library/Frameworks/AppKit.framework/Headers/NSBitmapImageRep.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:40,
                 from /Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m:5:
/Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m: In function '-[PanelView setAlpha:]':
/System/Library/Frameworks/AppKit.framework/Headers/NSImageRep.h:52:1: note: using '-(void)setAlpha:(BOOL)flag'
 - (void)setAlpha:(BOOL)flag;
 ^
/System/Library/Frameworks/AppKit.framework/Headers/NSImageRep.h:52:1: note: also found '-(void)setAlpha:(BOOL)flag'
/Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m:223:1: note: also found '-(void)setAlpha:(float)alpha'
 -(void)setAlpha:(float)alpha;
 ^
In file included from /System/Library/Frameworks/AppKit.framework/Headers/NSText.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:10,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSActionCell.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:15,
                 from /Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m:5:
/Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m: In function '-[TabView initWithFrame:]':
/System/Library/Frameworks/AppKit.framework/Headers/NSView.h:188:1: note: using '-(void)setAutoresizingMask:(NSUInteger)mask'
 - (void)setAutoresizingMask:(NSUInteger)mask;
 ^
/System/Library/Frameworks/AppKit.framework/Headers/NSView.h:188:1: note: also found '-(void)setAutoresizingMask:(NSUInteger)mask'
In file included from /System/Library/Frameworks/QuartzCore.framework/Headers/CAOpenGLLayer.h:6,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSOpenGLLayer.h:10,
                 from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:155,
                 from /Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m:5:
/System/Library/Frameworks/QuartzCore.framework/Headers/CALayer.h:730:1: note: also found '-(void)setAutoresizingMask:(unsigned int)_value'
 @end
 ^
In file included from /System/Library/Frameworks/AppKit.framework/Headers/NSText.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:10,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSActionCell.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:15,
                 from /Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m:5:
/Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m: In function '-[WindowView initWithContentRect:styleMask:backing:defer:withGadget:]':
/System/Library/Frameworks/AppKit.framework/Headers/NSView.h:188:1: note: using '-(void)setAutoresizingMask:(NSUInteger)mask'
 - (void)setAutoresizingMask:(NSUInteger)mask;
 ^
/System/Library/Frameworks/AppKit.framework/Headers/NSView.h:188:1: note: also found '-(void)setAutoresizingMask:(NSUInteger)mask'
In file included from /System/Library/Frameworks/QuartzCore.framework/Headers/CAOpenGLLayer.h:6,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSOpenGLLayer.h:10,
                 from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:155,
                 from /Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m:5:
/System/Library/Frameworks/QuartzCore.framework/Headers/CALayer.h:730:1: note: also found '-(void)setAutoresizingMask:(unsigned int)_value'
 @end
 ^
In file included from /System/Library/Frameworks/AppKit.framework/Headers/NSText.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:10,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSActionCell.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:15,
                 from /Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m:5:
/Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m: In function '-[ToolView initWithContentRect:styleMask:backing:defer:withGadget:]':
/System/Library/Frameworks/AppKit.framework/Headers/NSView.h:188:1: note: using '-(void)setAutoresizingMask:(NSUInteger)mask'
 - (void)setAutoresizingMask:(NSUInteger)mask;
 ^
/System/Library/Frameworks/AppKit.framework/Headers/NSView.h:188:1: note: also found '-(void)setAutoresizingMask:(NSUInteger)mask'
In file included from /System/Library/Frameworks/QuartzCore.framework/Headers/CAOpenGLLayer.h:6,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSOpenGLLayer.h:10,
                 from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:155,
                 from /Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod/cocoa.macos.m:5:
/System/Library/Frameworks/QuartzCore.framework/Headers/CALayer.h:730:1: note: also found '-(void)setAutoresizingMask:(unsigned int)_value'
 @end
 ^
clangclang: : warningclang: : warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/pub.mod/macos.mod'argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/timerdefault.mod'

clangclang: : warningwarning: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod':
argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod'
argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/pub.mod/macos.mod'clangclang: : warningwarning
: : argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/blitz.mod'argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/timer.mod'

clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/systemdefault.mod'
clangclang: : warningwarning: : argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod'argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/blitz.mod'

clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/blitz.mod'
clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/systemdefault.mod'
clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod'
clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/system.mod'
clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/keycodes.mod'
clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/hook.mod'
clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/blitz.mod'
clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/event.mod'
clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/cocoamaxgui.mod'
clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod'
clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/blitz.mod'
clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/maxgui.mod/maxgui.mod'
clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/pub.mod/macos.mod'



clang: warning: argument unused during compilation: '-I /Users/xxxx/bmx/BlitzMax/mod/brl.mod/systemdefault.mod'
```

Every subsequent attempt after that has just produced
```
[  0%] Compiling:appstub.macos.m
/Users/xxx/bmx/BlitzMax/mod/brl.mod/appstub.mod/appstub.macos.m: In function 'main':
/Users/xxx/bmx/BlitzMax/mod/brl.mod/appstub.mod/appstub.macos.m:100:2: error: stray '@' in program
  @autoreleasepool {
  ^
/Users/xxx/bmx/BlitzMax/mod/brl.mod/appstub.mod/appstub.macos.m:100:3: error: 'autoreleasepool' undeclared (first use in this function); did you mean 'NSAutoreleasePool'?
  @autoreleasepool {
   ^~~~~~~~~~~~~~~
   NSAutoreleasePool
/Users/xxx/bmx/BlitzMax/mod/brl.mod/appstub.mod/appstub.macos.m:100:3: note: each undeclared identifier is reported only once for each function it appears in
/Users/xxx/bmx/BlitzMax/mod/brl.mod/appstub.mod/appstub.macos.m:100:18: error: expected ';' before '{' token
  @autoreleasepool {
                  ^~
                  ;
Build Error: failed to compile (256) /Users/xxx/bmx/BlitzMax/mod/brl.mod/appstub.mod/appstub.macos.m%
```
Should I use an earlier release or is this a known bug?

**Comment by GWRon** [comment]
This "@autoreleasepool" is only supported by clang. 

What "xCode" version is installed - if any?

**Comment by melting-wax** [comment]
XCode version 6.2

**Comment by GWRon** [comment]
Hmm I used an older XCode and it compiled fine - so I doubt it is your clang version which I assumed first.

**Comment by GWRon** [comment]
Do you have "gcc" as symbolic link to clang or did you install a the real gcc?

**Comment by melting-wax** [comment]
Installed real gcc.

**Comment by GWRon** [comment]
Edited my reply above - give it a try.

**Comment by melting-wax** [comment]
Tried that before, but it was actually the result of MacPorts creating a gcc symlink.

Solved it with:
```
sudo port select --set gcc none
```

**Comment by GWRon** [comment]
Ahh ... cool. Glad you got it working.

Maybe Mac users should get a little hint for that possible problem. Thanks for making aware of that issue.
